---
- name: Run User setup role
  hosts: all
  become: yes
  connection: ssh
  become_method: sudo
  vars:
    user_home: /home/{{ deploy_user }}
    deploy_dir: "{{ user_home }}/deploy"
  roles:
    - java-app
